### ISSUE TITLE
Reprojection error of triangulation.

### ISSUE THREAD

**Issue by hunminkim98** [jasonyzhang/RayDiffusion#12]
Dear @jasonyzhang .
First of all, I really appreciated your great work. Thank you!

I have a question about the reprojection error of triangulation with ray diffusion's extrinsic. ( Intrinsic from checkerboard method )
When I triangulated OpenPose keypoints, the reprojection error was over 100px. ( tested several times )
It seems quite high, is this caused by something my mistake? or camera pose unstable? 
Did your tests show similar results?

Thanks again!
Best regards.

**Comment by jasonyzhang** [comment]
Hi, could you please give an example of what you mean? Our method does not give any 2D human keypoints.
