### ISSUE TITLE
Consulting about the train code

### ISSUE THREAD

**Issue by DavidYan2001** [jasonyzhang/RayDiffusion#14]
Dear authors,

Thanks for your nice work!

When I go through the code, only evaluation demo is provided. Do you have the plan to release the training code? 

I am interested in this research. Hope to hear from you soon.

**Comment by jasonyzhang** [comment]
We are planning to release the training code very soon. stay tuned...

**Comment by jasonyzhang** [comment]
The [dev branch](https://github.com/jasonyzhang/RayDiffusion/tree/dev) now has a V1 of the training code

**Comment by DavidYan2001** [comment]
Sincerely thank your!
