### ISSUE TITLE
Consulting for the equation inside the paper

### ISSUE THREAD

**Issue by DavidYan2001** [jasonyzhang/RayDiffusion#16]
Dear author,

Thanks for your nice work!

When I read the paper and the code, I find that "t = −R⊤c" is written in the paper. We know that "Rc+t=0" or "c =−R⊤t" and R is  orthonormal, so does this mean it should be "t = −R c" instead of "t = −R⊤c"?

Hope to hear from you soon, thanks!

**Comment by jasonyzhang** [comment]
You are correct. It should have been t=-Rc. This was corrected in the camera ready but not updated in the arxiv yet
