### ISSUE TITLE
predict_x0 parameter

### ISSUE THREAD

**Issue by liziwei-0** [jasonyzhang/RayDiffusion#17]
Hello, thank you for your great work on this project! 
﻿
I have a question regarding the predict_x0 parameter. Specifically, I am trying to understand its purpose and how it influences the training process. From what I can gather, it seems to determine the target during training, but I would like to get more clarity on this.

**Comment by liziwei-0** [comment]
I am currently working on a similar task and would like to better understand the training process and results. Could you please provide the training logs for reference?

**Comment by jasonyzhang** [comment]
For diffusion, predict_x0 trains a model that does x0 prediction instead of epsilon prediction. 
The regression model should always do x0 prediction since it's a regression model.
