### ISSUE TITLE
Weights are no longer available 

### ISSUE THREAD

**Issue by agosztolai** [jasonyzhang/RayDiffusion#18]
Hello, 

I am trying to download the weights for your model, but the Google Drive link no longer works. Can you please fix it?

**Comment by jasonyzhang** [comment]
Hi, Could you tell me what the error that you are getting is? The download link on the README (https://drive.google.com/file/d/1anIKsm66zmDiFuo8Nmm1HupcitM6NY7e/view) still works for me.

**Comment by agosztolai** [comment]
Thanks for checking! It all works now! Maybe it was a problem on Google’s side!

Best, 
Adam
