### ISSUE TITLE
How does batch_size affect the performance?

### ISSUE THREAD

**Issue by LiZizun** [jasonyzhang/RayDiffusion#20]
Thanks for your great works! I trained the model with effective batch of 32, which is half of the effective batch_size as the training command you provided. I got a model with poor performance after 450000 iterations. So I want to know if batch_size affects the model greatly or the configuration and training command you provided is different from which you used for training your final model?

**Comment by jasonyzhang** [comment]
I would expect that a batch size cut in half would require roughly twice as much training iterations. However, I would still expect the performance to be reasonable even if it is only half trained.

What do you mean by poor performance?

**Comment by LiZizun** [comment]
I loaded your checkpoint and it worked well, but when I train the model with smaller batch size, I got translation matrix with large error. Maybe I should train more iterations. Thanks!

**Comment by LiZizun** [comment]
I want to ask and discuss another question. Comparing with direction and point, why you choose to use direction and moment vector to describe rays? (Many other recent works also use Plücker rays to represent cameras, CAT3D, LaRa, etc) What is the beneficial of using Plücker rays?
