### ISSUE TITLE
Help in understanding the coordinate systems

### ISSUE THREAD

**Issue by aniket-gupta1** [jasonyzhang/RayDiffusion#21]
Hi, 
Thanks for your amazing work. 

I am having trouble understanding the coordinate frame of the predicted poses. 

When I run the collab notebook, the plotly visualizations are correct, but the coordinates of the points in the plotly plot do not correspond to the output. 

Can you please give some pointers on how to understand the coordinate frame of the model output?

Thanks

**Comment by jasonyzhang** [comment]
We follow the same camera convention as [Pytorch3D](https://pytorch3d.org/docs/cameras)

**Comment by aniket-gupta1** [comment]
Okay, So let's suppose I have 4 images that I registered using RayDiffusion and I get the output R and T. 

How can I get the the camera poses now in world frame? As in what is the model exactly predicting? The poses of cameras wrt the first camera or the poses of the cameras wrt world for each camera or vice-versa?
