### ISSUE TITLE
CO3D_ORDER_PATH does not find

### ISSUE THREAD

**Issue by jwubz123** [jasonyzhang/RayDiffusion#26]
Thanks a lot for the great wrok! 
I tried to use the co3d dataset for evaluation, but get FileNotFoundError: [Errno 2] No such file or directory: co3d/co3d_v2_random_order_1/hydrant.json' for [CO3D_ORDER_PATH](https://github.com/jasonyzhang/RayDiffusion/blob/f53303a2983f04b1ce6e60c967cecd1e1695b74f/ray_diffusion/dataset/co3d_v2.py#L20). I already run the precrocessing code but does not find this file, where can I get it?

**Comment by jasonyzhang** [comment]
You can download them from here: https://github.com/amyxlase/relpose-plus-plus/blob/main/eval.md#order-paths

**Comment by jwubz123** [comment]
Thanks a lot for your kind reply!
