### ISSUE TITLE
Camera Computation

### ISSUE THREAD

**Issue by VladimirYugay** [jasonyzhang/RayDiffusion#29]
Congrats on amazing work! 

I want to use ray representation for camera regression. I have camera poses in camera to world coordinate frame, and intrinsic with fx, fy, cx, cy and I don't do cropping. Right now I convert my poses and intrinsic to a PerspectiveCamera object, and then to rays similar to your codebase. However, the rays I'm getting are full of nans. 

Here's how I do it:

```
def c2w2camera(c2w: torch.Tensor, intrinsics: torch.Tensor, img_size: tuple):

    # intrinsics in nds coordinates
    height, width = img_size

    # https://github.com/facebookresearch/pytorch3d/blob/main/pytorch3d/renderer/cameras.py
    intrinsics_ndc = torch.zeros((intrinsics.shape[0], 4, 4)).to(intrinsics.device)
    intrinsics_ndc[:, :3, :3] = intrinsics.clone()
    intrinsics_ndc[:, 2, -1] = 1.0
    intrinsics_ndc[:, 3, 2] = 1.0

    # https://pytorch3d.org/docs/cameras
    s = min(img_size)
    intrinsics_ndc[:, 0, 0] = intrinsics_ndc[:, 0, 0] * 2.0 / s
    intrinsics_ndc[:, 1, 1] = intrinsics_ndc[:, 1, 1] * 2.0 / s
    intrinsics_ndc[:, 0, 2] = - (intrinsics_ndc[:, 0, 2] - width / 2.0) * 2.0 / s
    intrinsics_ndc[:, 1, 2] = - (intrinsics_ndc[:, 1, 2] - height / 2.0) * 2.0 / s

    return PerspectiveCameras(
        K=intrinsics_ndc, R=c2w[:, :3, :3], T=c2w[:, :3, 3], device=c2w.device, in_ndc=True)
```

then I call `camera_rays = rays.cameras_to_rays(cameras) ` with the function from your codebase. I assume that something is wrong in the way I compute camera objects from the poses and intrinsic. I also tried computing rays from world to camera, but the result is the same. Am I missing something?

**Comment by jasonyzhang** [comment]
I believe Pytorch3D uses world_to_cam and not cam_to_world, so it's likely your extrinsics need to be inverted. That still should not make the rays nans. Do you know which operation in cameras_to_rays is causing the nans? What do your K, R, and T tensors look like?

If you are converting your cameras from a different format, e.g. OpenCV, you can try [this](https://github.com/facebookresearch/pytorch3d/blob/main/pytorch3d/renderer/camera_conversions.py)

**Comment by VladimirYugay** [comment]
The nan happens when calling:
```
camera.unproject_points(xyd_grid.reshape(-1, 3), world_coordinates=False, from_ndc=True)
```
Changing the arguments `world_coordinates` or `from_ndc` does not change the result.

This happens specifically [here](https://github.com/facebookresearch/pytorch3d/blob/055ab3a2e3e611dff66fa82f632e62a315f3b5e7/pytorch3d/transforms/transform3d.py#L402). The `denom` variable is all zeroes.

I've attached the camera object as a txt file. You can load it by renaming it to `.pkl` file and load with:
```
import pickle
with open("camera.pkl", "rb") as f:
    loaded_cameras = pickle.load(f)
```

[camera.txt](https://github.com/user-attachments/files/18009815/camera.txt)

**Comment by jasonyzhang** [comment]
Why are you setting the intrinsics like this?

intrinsics_ndc[:, 2, -1] = 1.0
intrinsics_ndc[:, 3, 2] = 1.0

I think you should leave those coordinates as 0, and intrinsics_ndc[:, 3,
3] = 1

**Comment by VladimirYugay** [comment]
Hey there, thanks for the replies. The problem was indeed in the coordinate system. I now use `_cameras_from_opencv_projection` and everything clicks!
