### ISSUE TITLE
Convention about Camera and Ray

### ISSUE THREAD

**Issue by jytime** [jasonyzhang/RayDiffusion#8]
Hi Jason,

Thanks for the work! I am interested in trying "CAMERAS AS RAYS" in our ongoing project. After quickly checking the codes, it seems we can use [cameras_to_rays](https://github.com/jasonyzhang/RayDiffusion/blob/9c554a4433a696186e31f90bdec4d5e51e0a868f/ray_diffusion/utils/rays.py#L243) to convert pytorch3d cameras to PxP rays, and [rays_to_cameras_homography](https://github.com/jasonyzhang/RayDiffusion/blob/9c554a4433a696186e31f90bdec4d5e51e0a868f/ray_diffusion/utils/rays.py#L372C5-L372C31) to get the cameras back (with intrinsics). I was wondering:

1. Should we use cameras_to_rays and rays_to_cameras_homography for training? Should we keep the default flags, e.g., use_plucker=True? 
2. All the cameras are assumed to be NDC Pytorch3D camreas?

Any clarification is much appreciated!

Best,
Jianyuan

**Comment by jasonyzhang** [comment]
Hi Jianyuan!

Yes, default flags should be good. We always train with a 16x16 set of rays with Plucker coordinates. Just a heads up, when converting rays to cameras using rays_to_cameras_homography, I believe that the output will actually give you inverse focal length, so just do 1 / the focal length that it gives you.

Our code assumes all cameras are NDC Pytorch3D cameras.
